// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package email_test is a generated GoMock package.
package email_test

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/volam1999/gomail/internal/app/types"
)

// Mockservice is a mock of service interface.
type Mockservice struct {
	ctrl     *gomock.Controller
	recorder *MockserviceMockRecorder
}

// MockserviceMockRecorder is the mock recorder for Mockservice.
type MockserviceMockRecorder struct {
	mock *Mockservice
}

// NewMockservice creates a new mock instance.
func NewMockservice(ctrl *gomock.Controller) *Mockservice {
	mock := &Mockservice{ctrl: ctrl}
	mock.recorder = &MockserviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockservice) EXPECT() *MockserviceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Mockservice) Create(email *types.Email) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockserviceMockRecorder) Create(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mockservice)(nil).Create), email)
}

// FindAll mocks base method.
func (m *Mockservice) FindAll() (*[]types.Email, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].(*[]types.Email)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockserviceMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*Mockservice)(nil).FindAll))
}

// FindByEmailId mocks base method.
func (m *Mockservice) FindByEmailId(emailId string) (*types.Email, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmailId", emailId)
	ret0, _ := ret[0].(*types.Email)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmailId indicates an expected call of FindByEmailId.
func (mr *MockserviceMockRecorder) FindByEmailId(emailId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmailId", reflect.TypeOf((*Mockservice)(nil).FindByEmailId), emailId)
}
